### PR TITLE
mission6

### PR DESCRIPTION
**Pull request by w1729**

### CODE REVIEW

**Comment by MarcusWentz** [comment]
Website link hosted on IPFS using Fleek?

Do you have a 60 second YouTube demo?

**Comment by w1729** [comment]
IPFS : https://green-resonance-6286.on.fleek.co/

**Comment by w1729** [comment]
video and demo link added

**Comment by MarcusWentz** [comment]
I am unable to create a new map with the button. The island counter is not changing between maps. Please fix the following button: Cout Island should be Count Islands .

**Pull request merged**
