### PR TITLE
SupraOracles Order Book DEX Project completed 

### PR DESCRIPTION
**Pull request by Moganesan**
check mission/new/website folder

### CODE REVIEW

**Comment by MarcusWentz** [comment]
Please make sure all files are inside the mission folder. The following files should be moved for example: 
https://github.com/Moganesan/shardeum-missions/blob/main/missions/.DS_Store
https://github.com/Moganesan/shardeum-missions/tree/main/missions/new/website)

**Comment by MarcusWentz** [comment]
Do you have the website deployed to Fleek so it is public? 
Do you have a 60 second video demo? 
Please add these to the README for this mission.

**Comment by MarcusWentz** [comment]
Please move or delete:
https://github.com/Moganesan/shardeum-missions/blob/main/missions/.DS_Store

**Comment by Moganesan** [comment]
Video Demo : https://www.youtube.com/watch?v=yl0MUGEzzos
Deployment URL : https://supradex.vercel.app/

**Pull request closed without merging**
