### PR TITLE
final code changes and readme changes

### PR DESCRIPTION
**Pull request by bytes1**

### CODE REVIEW

**Comment by MarcusWentz** [comment]
I was able to beat the computer, and the game counted as the computer winning.
I also tied a game and the computer ended up winning. Please try to fix these issues.

**Comment by bytes1** [comment]
issues fixed. can you check again?

**Comment by MarcusWentz** [comment]
Please deploy contract to Liberty 2.1 for higher TPS:
https://docs.shardeum.org/network/endpoints#liberty-2x

**Comment by bytes1** [comment]
contract deployed

**Comment by MarcusWentz** [comment]
I was able to get the computer to win twice after making a move after the game already ended.
Please reset the board automatically once a player has won the game to avoid this issue.

**Comment by bytes1** [comment]
board reset fixed

**Comment by bytes1** [comment]
any other changes?

**Comment by MarcusWentz** [comment]
Looks good.
Thank you for the updates.

**Comment by MarcusWentz** [comment]
Please comment your Discord name in this PR so we can help give out the prize money.

**Comment by bytes1** [comment]
Discord name: infinity ü#6633

**Pull request merged**
