### PR TITLE
SupraOracles Order Book DEX Project completed

### PR DESCRIPTION
**Pull request by Moganesan**
#10 Old pull request closed by mistake

### CODE REVIEW

**Comment by MarcusWentz** [comment]
This file is still here and needs to be moved or deleted: 
https://github.com/Moganesan/shardeum-missions/blob/main/missions/.DS_Store

**Comment by MarcusWentz** [comment]
The swap only has BTC and USDT. It should include all pairs.

**Comment by Moganesan** [comment]
contract supports tokens and supports with supra oracle

**Comment by MarcusWentz** [comment]
I only see support for BTC and USDT on the website interface.
Please add all pairs supported with SupraOracles on Shardeum.

**Comment by Moganesan** [comment]
yes i will update the ui please check out the contract

**Comment by MarcusWentz** [comment]
Please update the website first.

**Comment by MarcusWentz** [comment]
Please add token logos on the website for the drop down.

**Comment by Moganesan** [comment]
Logo added to drop down menus

**Comment by MarcusWentz** [comment]
Closing since https://github.com/Shardeum/shardeum-missions/pull/12 has been merged.

**Pull request closed without merging**
