### PR TITLE
Mission/4

### PR DESCRIPTION
**Pull request by saurabhburade**
## Deployments
- Vercel ==> https://orderbook-dex.vercel.app/
- Fleek ==> https://cool-queen-3958.on.fleek.co/
- Video ==> https://youtu.be/dGKs5ovEEtQ

### CODE REVIEW

**Comment by Moganesan** [comment]
Video Demo : https://www.youtube.com/watch?v=yl0MUGEzzos
Deployment : https://supradex.vercel.app/

**Comment by MarcusWentz** [comment]
Please add all SupraOracle pairs supported on Shardeum.

**Comment by saurabhburade** [comment]
@MarcusWentz  All SupraOracle pairs supported on Shardeum are added.

**Comment by MarcusWentz** [comment]
What is your Discord? 
I would like to test this as well with tokens you have minted for swaps and the pools. We can discuss on Discord.

**Comment by saurabhburade** [comment]
Discord : Saurabh B#9234
Lets connect.

**Pull request merged**
