### PR TITLE
Finished

### PR DESCRIPTION
**Pull request by Kaiziron**

### CODE REVIEW

**Comment by MarcusWentz** [comment]
YouTube video demo link and hosted site using Fleek?

**Comment by Kaiziron** [comment]
https://super-cake-3763.on.fleek.co/missions/new/2/

**Comment by MarcusWentz** [comment]
Video demo on YouTube?

**Comment by Kaiziron** [comment]
https://youtu.be/KEs1URU-nFA

**Comment by MarcusWentz** [comment]
Nim should not be able to take 4 marbles on a turn.
This happened when I put 0 marbles with 12 marbles on the table. Please fix this.

**Comment by Kaiziron** [comment]
sorry, i think i misunderstand the description
```
      -take 1 marble if marblesOnTable == 4 or marblesOnTable == 8 or marblesOnTable == 12
      -take marblesOnTable%4 marbles (player with turn starting on 4 or 8 will likely lose)
      -take marblesOnTable marbles if marblesOnTable < 4
 ```
 so if one line is true, for example if marbles is 4,8,12, then no other line should be executed right?

**Comment by Kaiziron** [comment]
i have fixed that issue and updated it

**Comment by MarcusWentz** [comment]
With 

    -take 1 marble if marblesOnTable == 4 or marblesOnTable == 8 or marblesOnTable == 12

it should return.

Also if 

    -take marblesOnTable marbles if marblesOnTable < 4

all marbles are taken and the game ends with the computer winning.

**Comment by Kaiziron** [comment]
I have updated it, that it use if-else instead of returning if marbles is 4,8,12, but I think it should behave the same

**Comment by MarcusWentz** [comment]
Looks very cool. Great work. 

Please add the website and YouTube video demo to the README.
After that I will merge the PR.

**Comment by w1729** [comment]
wait for other requests also then decide better one.

**Comment by Kaiziron** [comment]
Just added on the README for mission 2

**Comment by Skandesh** [comment]
> wait for other requests also then decide better one.

Is there still time to submit? thought of giving a shot!

**Comment by MarcusWentz** [comment]
@Skandesh this PR has been merged, so this mission has ended.

**Pull request merged**
