### PR TITLE
mission 18 completed

### PR DESCRIPTION
**Pull request by AvinashNayak27**
Finished mission 18 smart contract  and deployed on Shardeum Liberety instead of Sphinx because of faucet issues and couldn't able to implement frontend

### CODE REVIEW

**Comment by MarcusWentz** [comment]
This should be shared as a private repo before a PR is opened.

**Comment by MarcusWentz** [comment]
What is your wallet address so I can send you some Betanet 1.X SHM (this should be deployed to Betanet 1.X not Liberty 2.X)?

You will need a website and a YouTube for your submission as well.

**Comment by Avinashnayak573** [comment]
0x2910135944f79d2B649209BC580fd9B6e73E82f1
I couldn't implement frontend because I thought deadline was today 7:30 pm IST

**Comment by MarcusWentz** [comment]
I will give more time if needed. 

Please create the website and the video demo.

**Comment by MarcusWentz** [comment]
I also sent you tokens now on Betanet 1.X:
https://explorer-sphinx.shardeum.org/account/0x2910135944f79d2b649209bc580fd9b6e73e82f1

**Comment by AvinashNayak27** [comment]
Ok I will send you private repo with website and video by 8th April 8:00 pm IST,Do I need dm you on discord or in mission discussion channel

**Comment by MarcusWentz** [comment]
Message me on Discord directly.

If you are making good progress and need more time let me know.

**Pull request closed without merging**
